# Generated by Django 3.2.10 on 2021-12-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images')),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
